import { useCallback } from 'react';
import { Link } from 'react-router-dom';
import { useServices } from '../../shared/ui/ServicesContext';
import { useQuery } from '../../shared/ui/useQuery';
import { ErrorNotice,SafetyNote,DemoBadge,formatNumber,formatTime } from '../../shared/ui/common';
import { getWeeklySummary } from '../../application/usecases/getWeeklySummary';
export function WeeklyPage({report=false}:{report?:boolean}){
 const {meals,glucose,clock,catalog}=useServices(),load=useCallback(()=>getWeeklySummary(meals,glucose,clock.now()),[meals,glucose,clock]),state=useQuery(load),summary=state.data;
 return <section className={report?'report':''}><div className="page-heading"><div><p className="eyebrow">BẢY NGÀY · TỪ NHỮNG ĐIỀU ĐÃ GHI</p><h1>{report?'Báo cáo tuần · Mâm An':'Tuần của tôi'}</h1></div>{report?<button className="primary no-print" disabled={!summary} onClick={()=>window.print()}>In / Lưu PDF</button>:<Link className="button" to="/report/weekly">Xem báo cáo ↗</Link>}</div><ErrorNotice error={state.error} retry={state.retry}/>{state.loading&&<p role="status">Đang tổng hợp…</p>}{summary&&<><p>{new Date(summary.periodStart).toLocaleDateString('vi-VN')} – {new Date(new Date(summary.periodEnd).getTime()-1).toLocaleDateString('vi-VN')}</p><div className="metric-grid"><div className="card"><span className="big-number">{summary.loggedMealCount}</span><p>bữa đã ghi</p></div><div className="card"><span className="big-number">{summary.glucoseReadings.length}</span><p>số đo đã nhập</p></div><div className="card"><h2>Dữ liệu của bạn</h2><p>{summary.meals.filter(m=>m.isDemo).length} bữa mẫu · {summary.meals.filter(m=>!m.isDemo).length} bữa tự ghi</p></div></div><div className="card"><h2>Carb ước tính theo ngày</h2><p className="muted">Từ các bữa đã ghi. Không có bản ghi không có nghĩa là không ăn.</p><div className="daily-list">{summary.dailyLoggedCarbEstimates.map(day=><div className="daily-row" key={day.localDate}><span>{day.localDate.slice(8)}/{day.localDate.slice(5,7)}</span><div className="bar-track"><div className="bar" style={{width:(day.totalKnownCarb===null?0:Math.max(2,day.totalKnownCarb/Math.max(1,...summary.dailyLoggedCarbEstimates.map(d=>d.totalKnownCarb??0))*100))+'%'}}/></div><span>{day.mealCount===0?'Chưa ghi':day.totalKnownCarb===null?'Chưa biết':formatNumber(day.totalKnownCarb)+' g'}{day.hasPartialMeals?' · Chưa đầy đủ':''}</span></div>)}</div>{summary.hasPartialMeals&&<SafetyNote kind="partial"/>}</div><div className="card"><h2>Các số đo đã nhập</h2><SafetyNote kind="glucose"/>{!summary.glucoseReadings.length?<p>Chưa có số đo trong tuần này.</p>:<div className="table-scroll"><table><thead><tr><th>Thời điểm</th><th>Số đo</th><th>Ghi nhận</th></tr></thead><tbody>{summary.glucoseReadings.map(g=><tr key={g.id}><td>{formatTime(g.measuredAt)}</td><td>{formatNumber(g.value)} {g.unit==='MG_DL'?'mg/dL':'mmol/L'}</td><td>{g.isDemo?<DemoBadge/>:'Tự ghi'}{g.mealId?' · Có liên kết bữa':''}</td></tr>)}</tbody></table></div>}</div><SafetyNote kind="weekly"/><p className="muted">Danh mục {catalog.getCatalogVersion()} · Nguồn ASEANFOODS 2014 · Lưu tại thiết bị</p></>}</section>;
}
